// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WF2upyh3fHaffr0cjeXD-zijI7dWGc4',
    appId: '1:502378600448:web:ca0dd817bf0ff94ff0e0e5',
    messagingSenderId: '502378600448',
    projectId: 'hackathon-869af',
    authDomain: 'hackathon-869af.firebaseapp.com',
    storageBucket: 'hackathon-869af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ08pf9aoqW5dr_IRx3PjNrGFBOSSne2g',
    appId: '1:502378600448:android:fb18d4144adf2eadf0e0e5',
    messagingSenderId: '502378600448',
    projectId: 'hackathon-869af',
    storageBucket: 'hackathon-869af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xuJVt8zLAvGFXFBgpb2LX8v4eZ_Y2x4',
    appId: '1:502378600448:ios:81d7cc783d7b5515f0e0e5',
    messagingSenderId: '502378600448',
    projectId: 'hackathon-869af',
    storageBucket: 'hackathon-869af.appspot.com',
    iosBundleId: 'com.example.hackaton',
  );
}
